default_stages: [push]
repos:
  - repo: local
    hooks:
      - id: run-backend-integration-test
        name: run all backend integration tests
        entry: make test-it
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        fail_fast: true
