FROM golang:1.22-alpine AS runner
LABEL maintainer="Tanawat Hongthai <ztrixack.th@gmail.com>"

# Set the environment variables for the go command:
ENV CGO_ENABLED=1 GO111MODULE=on GOOS=linux GOARCH=amd64

RUN apk --no-cache add build-base

# Set the working directory outside $GOPATH to enable the support for modules.
WORKDIR /src

# Start the application
CMD ["go", "run", "cmd/app/main.go"]