services:
  lazts-website:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lazts-website:1.0.0
    container_name: lazts-website
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    networks:
      - lazts

networks:
  lazts:
